export enum ETopicActionTypes {
    TOPICS_REQUEST = 'GET_TOPICS_REQUEST',
    TOPICS_REQUEST_SUCCESS = 'GET_TOPICS_SUCCESS',
    TOPICS_REQUEST_FAILURE = 'GET_TOPICS_FAILURE',

    CREATE_TOPIC_REQUEST = 'CREATE_TOPIC_REQUEST',
    CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS',
    CREATE_TOPIC_FAILURE = 'CREATE_TOPIC_FAILURE',

    VOTE_SUCCESS = 'VOTE_SUCCESS',

    LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS',
    CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS'
}
